version: "3.8"

services:
  db:
    image: ankane/pgvector
    container_name: pg-alexandria
    networks:
      - captain-overlay-network
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=hn
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    image: ghcr.io/julien040/alexandria-library
    container_name: web-server-alexandria
    ports:
      - 127.0.0.1:8080:3000
    depends_on:
      - db
    networks:
      - captain-overlay-network
    environment:
      - AZURE_AI_API_KEY
      - AZURE_AI_ENDPOINT
      - AZURE_AI_VERSION
      - AZURE_DEPLOYMENT_ID
      - POSTGRES_CONNECTION_STRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/hn

networks:
  captain-overlay-network:
    external: true
