version: "3.8"

services:
  pg-alexandria:
    image: ankane/pgvector
    container_name: pg-alexandria
    networks:
      - captain-overlay-network
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=hn
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web-server-alexandria:
    image: ghcr.io/julien040/alexandria-library:latest
    container_name: web-server-alexandria
    depends_on:
      - pg-alexandria
    networks:
      - captain-overlay-network
    environment:
      - AZURE_AI_API_KEY
      - AZURE_AI_ENDPOINT
      - AZURE_AI_VERSION
      - AZURE_DEPLOYMENT_ID
      - POSTGRES_CONNECTION_STRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg-alexandria:5432/hn

networks:
  captain-overlay-network:
    external: true
